apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: super-api
  name: super-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: super-api
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: super-api
    spec:
      containers:
      - image: draft7787.azurecr.io/super-api
        name: super-api
        ports:
        - containerPort: 8080
        resources: {}
status: {}
